cache:
  paths:
    - .m2/repository

services:
  - mongo

test:jdk-8:
  image: maven:3-jdk-8
  script: mvn clean package -Dgpg.skip=true

test:jdk-7:
  image: maven:3-jdk-7
  script: mvn clean package -Dgpg.skip=true