cache:
  paths:
    - /root/.m2/repository/

services:
  - mongo:3.2

test:jdk-8:
  image: maven:3-jdk-8
  script: export MARK_MONGO_HOST="mongo" && mvn clean package -Dgpg.skip=true

test:jdk-7:
  image: maven:3-jdk-7
  script: export MARK_MONGO_HOST="mongo" && mvn clean package -Dgpg.skip=true
