language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
services:
  - mongodb
install: cd mark && mvn --quiet install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
script: travis_wait mvn clean verify

#after_success:
#  - mvn clean cobertura:cobertura coveralls:report
