# A small configuration
# check folder modules-small to see
# which modules are activated
---
mongo_host:     127.0.0.1
mongo_port:     27017
mongo_db:       MARK
mongo_clean:    true

update_interval:  3

server_host:    127.0.0.1
server_port:    8080

adapter_class:  netrank.LinkAdapter  

modules:        ./modules

webserver_root: ../../ui
