# A very basic configuration
# no module is activated
# => no data or detection agent
#    server uses the DummySubjectAdapter
---
mongo_host:     127.0.0.1
mongo_port:     27017
mongo_db:       MARK

server_host:    127.0.0.1
server_port:    8080

webserver_root: ./ui
log_directory:  ./logs
modules:        ./modules
